/*
 * This source file was generated by the Gradle 'init' task
 */
package io.levendel;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(null);
    }
}
